kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-alert-routing
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alert-routing-edit

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-monitoring-edit
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-monitoring-rules-edit
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-rules-edit

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-monitoring-rules-view
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-rules-view